### ISSUE TITLE
Get the same behavior for native bindings

### ISSUE THREAD

**Issue by Kagami** [brianc/node-pg-query-stream#8]
Hi. Sorry for the noob question.
The README for this library says that it only works for pure JS node-postgres bindings. Is it possible to get the same behavior for native bindings? Ideally with the same API.

It would be useful for the [Knex](https://github.com/tgriesser/knex) library: now it supports only pure JS bindings because of the pg-query-stream use: https://github.com/tgriesser/knex/blob/master/lib/dialects/postgres/runner.js#L21-L28 If pg-query-stream supports native bindings as well Knex will transparently support both native and pure JS bindings.

**Comment by sheerun** [comment]
+1

**Comment by brianc** [comment]
Unfortunately it's not possible to get the same behavior with the native bindings.  Libpq abstracts _on top of_ the postgres binary protocol and does not expose any functions to access cursors directly at the protocol level.  I suppose something could be done to send textual commands to create, consume, and close cursors but that would require a different interface all together because the user would have to input the command to create the cursor.
